// Copyright 2026 shing1211
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package conformance holds the committed wire-conformance fixtures and the
// manifest that records where each one came from.
//
// # Why this exists
//
// Most of the SDK's local-server tests build a response body by marshalling the
// SDK's own Go type and then assert the SDK decodes it. For example
// brokerfd/assets_test.go encodes a []FDPosition and asserts TestGetFDPositions
// reads it back. That establishes the type is self-consistent. It cannot
// establish the type matches the endpoint, and the gap is not theoretical: the
// documented response for GET /broker/assets/positions/list requires
// cost_price, last_price and unrealized_profit_loss, while FDPosition tags
// average_cost, market_value and unrealized_pl. The self-round-trip passes, and
// the live endpoint returns three zero-valued money.Money with no error.
//
// The cure is a body that came from somewhere other than the SDK. Every file
// under testdata outside live/ is a minimal conforming instance of the 200
// response schema Webull publishes for that endpoint, so the fixture is a
// snapshot of the documentation and the SDK type is what has to agree with it.
//
// The tree holds a second kind of file, and the exception has to be named here
// because this is a public package and its documentation is what a reader trusts
// about its own tree. testdata/live/ holds response skeletons captured from the
// running sandbox by examples/live-probe: the shape of what a server answered,
// with every value replaced by a placeholder. They are not instances of any
// published schema, and none of the five checks below applies to them as
// written -- a fixture is a restatement of a page, and a skeleton is one
// observation of one response. testdata/live-manifest.json indexes them and
// live/README.md says what they are from inside the tree itself.
//
// live.go is what reads them, and it reads them by running the same five checks
// against them: a skeleton is a body, and CompareBody takes one. So the live tree
// is evidence about this SDK, where every other file in the tree is evidence
// about Webull's documentation, and the two are kept apart throughout: a separate
// comparison, a separate set of directions, a separate baseline in
// live-divergences.json, and a separate gate. Recording a live finding in
// known-divergences.json would put 25 documented rows and N live rows in one
// backlog when the live rows are not claims about this SDK at all.
//
// The split is a partition rather than an exemption, and it is enforced rather
// than asserted. TestManifestDescribesTheWholeTree walks the embedded tree and
// holds each half to its own index: a file outside live/ must be named by
// testdata/manifest.json and a file under live/ must be named by
// testdata/live-manifest.json, so a skeleton with no provenance is still a
// failure and only the index it must appear in has changed. The tree's own README
// is described by neither, because it is prose about the tree rather than
// evidence in it. On the generator side, tools/conformance/gen_fixtures.py
// excludes live/ and live-manifest.json by exact first path segment, so --check
// does not report committed evidence as a deleted fixture; its seven self-test
// checks pin both edges of that exclusion.
//
// # Where the checking lives, and why
//
// The comparison lives here, in Go, and not in the generator. A fixture
// regenerated by the same logic that consumes it cannot fail: a bug in the
// generator would satisfy the very test meant to catch a bug in the SDK. The
// split is deliberate and one-directional.
//
//   - tools/conformance/gen_fixtures.py emits data only. It reads the
//     gitignored docgen cache, emits a fixture per endpoint, and records
//     provenance. No fixture byte is derived from, or checked against, a Go
//     type, so it is structurally incapable of reproducing an SDK-shaped bug.
//   - This package and its tests read the committed bytes. Nothing regenerates
//     them during a test run, so a fixture is what a reviewer can open, diff,
//     and trace back to a named page on developer.webull.{hk,com}.
//
// One qualification, because "the generator never reads Go" would be false. The
// manifest records the path each SDK method sends, and docgen's
// resolve_method_path answers that by scanning Go path constants, so a
// generation run does open .go files: 2,234 opens across 100 files in the nine
// SDK packages. Two things keep that harmless. The scan reads path strings,
// never struct fields, so it cannot inform a fixture's property names even in
// principle; and the result annotates only Fixture.SDKPath and SDKPathMatch,
// never a fixture. The generator installs a sys.addaudithook that prints every
// .go file it opened and fails on any outside that scan, so the boundary is
// enforced rather than asserted.
//
// make conformance-fixtures is the gate that keeps the two honest: it
// regenerates in memory and fails if the result differs from what is committed,
// so drift is a signal rather than a silent regeneration.
//
// # Layout
//
//	testdata/manifest.json                     provenance and per-fixture checks
//	testdata/<area>/<METHOD>-<path>.json       one fixture per documented endpoint
//	testdata/live-manifest.json                the live tree's own index
//	testdata/live/README.md                    what the live tree is, in the tree
//	testdata/live/<area>/<METHOD>-<path>.json  one skeleton per captured endpoint
//	known-divergences.json                    the recorded documentation baseline
//	live-divergences.json                     the recorded live baseline
//	symbols.go                                the symbol-to-type table
//	envelopes.go                              unexported decode targets, read from source
//	shapes.go                                 the five comparisons
//	live.go                                   the live comparison, its buckets and baseline
//	liveskeleton.go                           the committed skeleton form and its inverse
//
// The <area> directory is the tools/webull-docgen AREAS manifest key, so a
// fixture's directory says which part of the API surface it documents. The file
// name repeats the documented method and path, which makes a fixture
// identifiable from a terminal prompt without opening the manifest. A skeleton
// repeats the name of the documentation fixture for the same endpoint, so the two
// trees join row for row on the name and nothing has to be mapped between them.
//
// What the live tree rests on, and where each half of it is checked, is in
// fixtures_test.go rather than here: TestLiveSkeletonsCarryNoValue walks the
// committed bytes and fails on any leaf that is not the placeholder for its kind
// and on any member name that could itself be a value the server sent, and
// TestLiveManifestDeclaresItHoldsNoValues holds the index to the claim it makes
// about its own contents. Neither the skeleton files nor the manifest is consumed
// by divergence_test.go, and a skeleton is not a fixture: it is one observation of
// one response, where a fixture is a restatement of one published schema.
//
// The committed skeletons are stored deduplicated -- distinct element shapes with
// a count beside each, which is the evidence rather than the repetition -- so a
// skeleton is not itself a body the comparison can read. liveskeleton.go holds
// the form and its inverse, ExpandSkeleton turns the committed bytes back into
// the reduced tree, and the leak gate walks the committed form rather than the
// expanded one, so the guarantee is asserted against the bytes a reader can open.
//
// # What "the committed bytes" means on a given checkout
//
// The tree is embedded, and embedding reads the working tree, so the bytes a run
// compares are the bytes the checkout materialised -- which are not always the
// bytes that were committed. The manifest records byte counts, and the generator
// writes LF, so a checkout that applies a line-ending policy embeds a longer
// file than the manifest describes: this repository's .gitattributes is
// `* text=auto` and windows-latest ships core.autocrlf=true, so CRLF is that
// runner's default rather than a choice. The fixture assertions therefore
// compare byte counts with CRLF collapsed to LF, and separately refuse a
// carriage return that is not part of a CRLF, so the tolerated set is exactly
// "a CRLF checkout" and not "whatever the checkout did". Everything structural --
// valid JSON, the documented top-level kind, the required names, the distinct
// property-name count -- is line-ending policy independent already, and one
// basis of a fixture's meaning. See committedLength in fixtures_test.go, which
// also records what the tolerance gives up: a length is not a digest, so a
// length-preserving content edit was never detectable by the byte count, before
// this or after it.
//
// # What is compared against what
//
// divergence_test.go resolves each manifest row to a Go type through the
// hand-written table in symbols.go, decodes the committed fixture into it, and
// runs five checks in descending order of how much they prove:
//
//  1. every name the page marks required reaches a json tag;
//  2. every name the page declares without marking required reaches a json tag,
//     which runs only where a page publishes no required list at all and on
//     weaker evidence: a required name is a promise, a declared name is a
//     description of one response, and a 2 is reported separately from a 1 so
//     the strength stays readable off a baseline entry;
//  3. the documented top level, and an array's element kind, match the type the
//     method decodes into;
//  4. each required name the SDK does tag has a compatible Go type;
//  5. the documented instance unmarshals without error -- reported last,
//     because a decode that succeeds is consistent with a type that ignores
//     every documented name and so proves very little.
//
// Three limits on those five are part of the design rather than oversights, and
// all three are stated here because a reader of the counts needs them.
//
// A row is compared only when its SDK method sends the path the page documents.
// Five rows are not: the method sends some other path, so the page is not that
// call's contract and a schema difference between them is not a defect claim
// about this SDK. Those rows claim nothing and say so, which is a third state
// beside conforming and divergent, and the count is in the baseline's coverage
// block rather than in prose here. The path defects themselves are unaffected --
// TestDefectivePathRowsAreDocumented lists all five.
//
// Checks 1 and 2 are floors, not totals. They consider the union of json tags at
// every depth of the compared type, because encoding/json flattens a response
// body into one name space, so a documented name the SDK carries only inside a
// nested object counts as covered. The names that reached a tag only from below
// are printed per row by TestObservedDivergenceReport under the
// required-name-depth skip.
//
// Check 2 skips three data.* rows that decode into a free-form map, which carries
// every documented name and declares none of them; between them the three pages
// declare 105 names, so a missing name there would be the harness's error rather
// than a finding. It also skips any row whose page declares names at a level other
// than the one it reads, which is an array of scalars. One row is recorded as
// declared-inventory-empty instead: its page declares no property name at all, so
// nothing on it could be compared, and filing that as a pass would make a page
// nobody can examine read as a page that examined clean.
//
// Six decode targets are response envelopes the SDK package does not export, so
// they cannot be named in a reflect.TypeOf call from here. They are read from the
// SDK sources instead, by envelopes.go, and the rebuilt type is compared field by
// field against the declaration on every run.
//
// The current tree does not pass those checks, and is not expected to. The
// divergences it has are recorded in known-divergences.json, each with a reason
// and a pointer to where the defect is written down, and the gate fails only when
// the observed set stops being exactly that set. No entry is waived. See
// baseline.go for why a baseline rather than a skip list, and for why a required
// reason, while it blocks a reasonless entry, does not make a reason true.
//
// # What the live comparison adds, and what it cannot
//
// live.go runs the same five checks against the live tree, and everything it
// rests on is in its own file comment: the two runs, the classification, the key,
// and the limit that checkShape reads the manifest rather than the body. The two
// short statements that belong here are the ones a reader of this package's
// documentation should not have to go looking for.
//
// A live finding is a claim about Webull's server, so it is recorded in
// live-divergences.json and not in known-divergences.json. The documented
// baseline holds 25 entries and this one holds 13 from a single run against one
// host; reading them as one backlog of 38 would be wrong, because the live rows
// are not claims about this SDK. TestLiveFindingsAreAttributable exists because
// the documented baseline's recorded failure was a reason repeated across many
// entries, which satisfies a required-field check perfectly.
//
// Four of the 13 are the captured bodies the SDK's own type could not decode, and
// that is the class the documented comparison is structurally blind to: a page
// and a fixture made to agree with each other decode cleanly whether or not
// either matches the server. One of the four -- data.GetFuturesTick -- is a name
// the page and the SDK agree on and the server spells differently, which no
// amount of reading the documentation could have found.
//
// Everything here rests on one authorised run against one sandbox. A finding is
// what api.sandbox.webull.hk answered once, and nothing in this package says what
// production answers.
//
// # Scope of the committed tree
//
// A fixture is a minimal conforming instance: for each object node its required
// properties, for each leaf the inline example, for each array one element.
// Optional properties are omitted, which is what makes it minimal and what
// makes it small. The cost is real and is recorded rather than hidden: 101 of
// the 193 fixtures come from pages that declare no required list at the top
// level or on the array element, so those instances carry no name from Webull
// at all. Manifest.Checks.DeclaresRequired is false for exactly those, and
// Checks.DeclaredTopLevelNames and Checks.DeclaredElementNames carry the full
// name inventory so a consumer can still check SDK tag coverage for names the
// instance does not carry. A false DeclaresRequired is not a statement that
// the names were verified.
//
// # What this package does not cover
//
// The 29 broker.* symbols are not compared. broker/ is a separate Go module, so
// its types are not importable from here without a go.mod change, and a test
// inside this package that pretended otherwise would be asserting something
// untrue. Those endpoints need their own test inside broker/, and this file
// records their absence rather than working around it: the gate's coverage
// block names all 29, so the gap is a number in a committed file and not a
// caveat in prose.
package conformance
